services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timeclock_app
    network_mode: host          # <- full host networking
    env_file:
      - .env
    restart: unless-stopped
